version: '3.9'

services:
  api:
    build: 
      context: ./api
    restart: always
    depends_on:
      - db
    environment:
      - POSTGRES_DB
      - POSTGRES_HOST
      - POSTGRES_PASSWORD
      - POSTGRES_PORT
      - POSTGRES_USER

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: always
    volumes:
      - ./persistent_data/log/nginx:/var/log/nginx/
    ports:
      - 1337:80
    depends_on:
      - api
    environment: 
      - API_BASE_URL

  db:
    image: postgres:14.2
    restart: always
    volumes:
      - ./persistent_data/pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
